# Generated by Django 3.0 on 2019-12-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
                ('comic_pic', models.ImageField(default='pic_folder/no_img.jpg', upload_to='pic_folder/')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
